name: WakaTime Stats Update

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          SHOW_PROJECTS: false # Set to true if you want to show which repos you spent time on