name: WakaTime Stats Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    permissions:
      contents: write # This forces GitHub to allow the bot to save the README
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true